### ISSUE TITLE
RotatingFileStreamError: Too many destination file attempts

### ISSUE THREAD

**Issue by DF1229** [DF1229/portfolio#36]
node:events:504
      throw er; // Unhandled 'error' event
      ^

RotatingFileStreamError: Too many destination file attempts
    at RotatingFileStream.findName (/home/dfaber/portfolio/node_modules/rotating-file-stream/dist/cjs/index.js:182:15)
    at async RotatingFileStream.move (/home/dfaber/portfolio/node_modules/rotating-file-stream/dist/cjs/index.js:186:26)
    at async Timeout.set (/home/dfaber/portfolio/node_modules/rotating-file-stream/dist/cjs/index.js:286:21)
Emitted 'error' event on RotatingFileStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'RFS-TOO-MANY'
}

**Comment by DF1229** [comment]
Error appears at exactly 00:00 UTC

**Comment by DF1229** [comment]
Server has not crashed for two days now, assuming this issue was caused by multiple instances of the project running instead of the combination of an HTTP and HTTPS server.

Closing.
